
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public final class Consulta extends javax.swing.JInternalFrame {
       private DefaultTableModel  modelo;
       int contador = 0;
    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        CargarInterfaz();
        CargarDatos();
    }
    public void CargarInterfaz(){
        String datos[][] = {};
        String columna [] = {"No. Empleado","RFC", "Nombre", "Apellido", "Dirección","Departamento","Sexo"};
        modelo = new DefaultTableModel (datos,columna);
        TblEmpleados.setModel(modelo);
    }
    
    public void CargarDatos(){
        Empleados emp;
        for (int i = 0; i<Captura.contenedor.size(); i++){
            emp =(Empleados) Captura.contenedor.get(i);
            modelo.insertRow(contador, new Object[]{});
            modelo.setValueAt(emp.getId(), contador ,0);
            modelo.setValueAt(emp.getRfc(), contador ,1);
            modelo.setValueAt(emp.getNombre(), contador ,2);
            modelo.setValueAt(emp.getApellidos(), contador ,3);
            modelo.setValueAt(emp.getDireccion(), contador ,4);
            modelo.setValueAt(emp.getDepartamento(), contador ,5);
            modelo.setValueAt(emp.getSexo(),contador,6);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblEmpleados = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Recuperacion de un Registro");

        TblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TblEmpleados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TblEmpleados.setRowHeight(24);
        jScrollPane1.setViewportView(TblEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable TblEmpleados;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
